BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Vote` (
	`VoterPlayerID`	TEXT NOT NULL,
	`FactID`	TEXT NOT NULL,
	`GuessPlayerID`	TEXT NOT NULL,
	FOREIGN KEY(`VoterPlayerID`) REFERENCES `Player`(`ID`),
	FOREIGN KEY(`FactID`) REFERENCES `Player`(`FactID`),
	FOREIGN KEY(`GuessPlayerID`) REFERENCES `Player`(`ID`),
	PRIMARY KEY(`VoterPlayerID`,`FactID`)
);
CREATE TABLE IF NOT EXISTS `Player` (
	`ID`	TEXT NOT NULL UNIQUE,
	`GameID`	TEXT NOT NULL,
	`Name`	TEXT NOT NULL,
	`Symbol`	TEXT NOT NULL,
	`Color`	TEXT NOT NULL,
	`Fact`	TEXT NOT NULL,
	`FactID`	TEXT NOT NULL UNIQUE,
	`Score`	NUMERIC DEFAULT 0,
	FOREIGN KEY(`GameID`) REFERENCES `Game`(`ID`),
	PRIMARY KEY(`ID`)
);
CREATE TABLE IF NOT EXISTS `Game` (
	`ID`	TEXT NOT NULL UNIQUE,
	`AdminToken`	TEXT NOT NULL,
	`Name`	TEXT NOT NULL,
	`Status`	INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);
COMMIT;
